"""
Spec Parser — reads and structures cc-sdd specification files.

Parses the Markdown files generated by cc-sdd (requirements.md, design.md,
tasks.md, brief.md) into structured Python dicts that can be sent to the
frontend as JSON.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class SpecFile:
    """Represents a single spec file with metadata."""
    name: str
    path: str
    content: str
    size: int
    last_modified: float


@dataclass
class Requirement:
    """A single requirement parsed from requirements.md."""
    id: str
    title: str
    description: str
    acceptance_criteria: List[str] = field(default_factory=list)


@dataclass
class Task:
    """A single task parsed from tasks.md."""
    id: str
    title: str
    description: str
    status: str = "pending"  # pending | in_progress | done
    boundary: str = ""
    depends: str = ""


@dataclass
class SpecSummary:
    """Summary of a complete specification."""
    name: str
    path: str
    has_brief: bool = False
    has_requirements: bool = False
    has_design: bool = False
    has_tasks: bool = False
    requirement_count: int = 0
    task_count: int = 0
    tasks_completed: int = 0
    language: str = "es"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

class SpecParser:
    """Parses cc-sdd specification directories."""

    def __init__(self, kiro_dir: Path) -> None:
        self.kiro_dir = kiro_dir
        self.specs_dir = kiro_dir / "specs"

    def list_specs(self) -> List[SpecSummary]:
        """List all specification directories with their status."""
        if not self.specs_dir.exists():
            return []

        specs: List[SpecSummary] = []
        for entry in sorted(self.specs_dir.iterdir()):
            if not entry.is_dir():
                continue

            summary = SpecSummary(
                name=entry.name,
                path=str(entry),
            )

            # Check which files exist
            summary.has_brief = (entry / "brief.md").exists()
            summary.has_requirements = (entry / "requirements.md").exists()
            summary.has_design = (entry / "design.md").exists()
            summary.has_tasks = (entry / "tasks.md").exists()

            # Count requirements
            if summary.has_requirements:
                reqs = self.parse_requirements(entry.name)
                summary.requirement_count = len(reqs)

            # Count tasks
            if summary.has_tasks:
                tasks = self.parse_tasks(entry.name)
                summary.task_count = len(tasks)
                summary.tasks_completed = sum(
                    1 for t in tasks if t.status == "done"
                )

            # Read spec.json for language if it exists
            spec_json = entry / "spec.json"
            if spec_json.exists():
                try:
                    data = json.loads(spec_json.read_text(encoding="utf-8"))
                    summary.language = data.get("language", "es")
                except Exception:
                    pass

            specs.append(summary)

        return specs

    def get_spec_file(self, spec_name: str, filename: str) -> Optional[SpecFile]:
        """Get a specific file from a spec directory."""
        file_path = self.specs_dir / spec_name / filename
        if not file_path.exists():
            return None

        content = file_path.read_text(encoding="utf-8")
        stat = file_path.stat()
        return SpecFile(
            name=filename,
            path=str(file_path),
            content=content,
            size=len(content),
            last_modified=stat.st_mtime,
        )

    def get_all_spec_files(self, spec_name: str) -> List[SpecFile]:
        """Get all files from a spec directory."""
        spec_dir = self.specs_dir / spec_name
        if not spec_dir.exists():
            return []

        files: List[SpecFile] = []
        for f in sorted(spec_dir.iterdir()):
            if f.is_file():
                try:
                    content = f.read_text(encoding="utf-8")
                    stat = f.stat()
                    files.append(SpecFile(
                        name=f.name,
                        path=str(f),
                        content=content,
                        size=len(content),
                        last_modified=stat.st_mtime,
                    ))
                except Exception as exc:
                    logger.warning("Could not read %s: %s", f, exc)

        return files

    def parse_requirements(self, spec_name: str) -> List[Requirement]:
        """Parse requirements.md into structured requirements."""
        spec_file = self.get_spec_file(spec_name, "requirements.md")
        if not spec_file:
            return []

        requirements: List[Requirement] = []
        content = spec_file.content

        # Pattern: ## REQ-001: Title
        # or ## 1. Title
        req_pattern = re.compile(
            r"^##\s+(?:REQ-(\d+):?\s+|(\d+)\.\s+)(.+)$",
            re.MULTILINE,
        )

        matches = list(req_pattern.finditer(content))
        for i, match in enumerate(matches):
            req_id = match.group(1) or match.group(2) or str(i + 1)
            title = match.group(3).strip()

            # Get content between this heading and the next
            start = match.end()
            end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
            body = content[start:end].strip()

            # Extract acceptance criteria
            criteria: List[str] = []
            ac_match = re.search(
                r"(?:Acceptance Criteria|Criterios de Aceptación|Given|Dado)"
                r".*?(?=\n##|\Z)",
                body,
                re.DOTALL | re.IGNORECASE,
            )
            if ac_match:
                for line in ac_match.group().split("\n"):
                    line = line.strip()
                    if line.startswith(("-", "*", "•")):
                        criteria.append(line.lstrip("-*• "))

            requirements.append(Requirement(
                id=f"REQ-{req_id}",
                title=title,
                description=body[:500],
                acceptance_criteria=criteria,
            ))

        return requirements

    def parse_tasks(self, spec_name: str) -> List[Task]:
        """Parse tasks.md into structured tasks."""
        spec_file = self.get_spec_file(spec_name, "tasks.md")
        if not spec_file:
            return []

        tasks: List[Task] = []
        content = spec_file.content

        # Pattern: ## Task 1: Title or ## 1. Title
        task_pattern = re.compile(
            r"^##\s+(?:Task\s+(\d+):?\s+|(\d+)\.\s+)(.+)$",
            re.MULTILINE,
        )

        matches = list(task_pattern.finditer(content))
        for i, match in enumerate(matches):
            task_id = match.group(1) or match.group(2) or str(i + 1)
            title = match.group(3).strip()

            # Get content between this heading and the next
            start = match.end()
            end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
            body = content[start:end].strip()

            # Check for status markers
            status = "pending"
            if re.search(r"\[x\]|\[✅\]|DONE|COMPLETED|Completad[oa]", body, re.IGNORECASE):
                status = "done"
            elif re.search(r"IN.PROGRESS|En.progreso", body, re.IGNORECASE):
                status = "in_progress"

            # Extract boundary
            boundary_match = re.search(r"_Boundary:_\s*(.+?)(?:\n|$)", body)
            boundary = boundary_match.group(1).strip() if boundary_match else ""

            # Extract depends
            depends_match = re.search(r"_Depends:_\s*(.+?)(?:\n|$)", body)
            depends = depends_match.group(1).strip() if depends_match else ""

            tasks.append(Task(
                id=f"TASK-{task_id}",
                title=title,
                description=body[:500],
                status=status,
                boundary=boundary,
                depends=depends,
            ))

        return tasks

    def extract_mermaid_diagrams(self, spec_name: str) -> List[str]:
        """Extract Mermaid diagram code blocks from design.md."""
        spec_file = self.get_spec_file(spec_name, "design.md")
        if not spec_file:
            return []

        # Match ```mermaid ... ``` blocks
        pattern = re.compile(
            r"```mermaid\s*\n(.*?)```",
            re.DOTALL,
        )

        return [m.group(1).strip() for m in pattern.finditer(spec_file.content)]

    def get_brief(self, spec_name: str) -> Optional[str]:
        """Get the brief.md content."""
        spec_file = self.get_spec_file(spec_name, "brief.md")
        return spec_file.content if spec_file else None

    def get_roadmap(self) -> Optional[str]:
        """Get the roadmap.md content (lives at .kiro/ root level)."""
        roadmap = self.kiro_dir / "roadmap.md"
        if roadmap.exists():
            return roadmap.read_text(encoding="utf-8")
        return None
